name: Deploy Pigs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.H_SERVER }}
          username: ${{ secrets.H_USER }}
          password: ${{ secrets.H_PASS }}
          server-dir: /www/domik-svinok.ru/
          exclude: "[**/.git*/**, **/web/**, **/api/**, **/db/**, **/config/db.php]"